#!/usr/bin/env python3
# Copyright (c) 2026 Mikhail Svarichevsky <mikhail@zeptobars.com>
# SPDX-License-Identifier: MIT
"""Generate the public single-file A1 decoder header."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARTS = (
    ("src/patch_config.h", ()),
    ("src/rc_models.h", ('#include "patch_config.h"',)),
    ("src/patch_apply.h", ('#include "rc_models.h"',)),
)


def filtered_text(rel: str, skip_lines: tuple[str, ...]) -> str:
    path = ROOT / rel
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip() in skip_lines:
            out.append(f"/* {line.strip()} - inlined by gen_single_header.py */")
        else:
            out.append(line)
    return "\n".join(out).rstrip() + "\n"


def generate() -> str:
    chunks = [
        "/*",
        " * Generated public single-header A1 decoder.",
        " * Source headers, in order:",
        " *   src/patch_config.h",
        " *   src/rc_models.h",
        " *   src/patch_apply.h",
        " * Include from one update translation unit to avoid duplicate decoder text.",
        " * Do not edit this file by hand; regenerate with: make decoder-header",
        " */",
        "",
    ]
    for rel, skips in PARTS:
        chunks.append(f"/* ===== begin {rel} ===== */")
        chunks.append(filtered_text(rel, skips).rstrip())
        chunks.append(f"/* ===== end {rel} ===== */")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", help="path to write, or - for stdout")
    args = parser.parse_args()

    text = generate()
    if args.output == "-":
        print(text, end="")
    else:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
