#!/usr/bin/env python3
# Copyright (c) 2026 Mikhail Svarichevsky <mikhail@zeptobars.com>
# SPDX-License-Identifier: MIT
"""Generate the public single-file A1 decoder header."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import tempfile


ROOT = Path(__file__).resolve().parents[1]


def is_public_include(line: str, public_names: set[str]) -> bool:
    text = line.strip()
    if not text.startswith('#include "') or text.count('"') < 2:
        return False
    return text.split('"', 2)[1] in public_names


def filtered_text(rel: str, public_names: set[str]) -> str:
    path = ROOT / rel
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if is_public_include(line, public_names):
            out.append(f"/* {line.strip()} - inlined by gen_single_header.py */")
        else:
            out.append(line)
    return "\n".join(out).rstrip() + "\n"


def generate(headers: list[str]) -> str:
    chunks = [
        "/*",
        " * Generated public single-header A1 decoder.",
        " * Source headers, in order:",
        *(f" *   {rel}" for rel in headers),
        " * Include from one update translation unit to avoid duplicate decoder text.",
        " * Wire macro overrides MUST use the same names and values as the matching encoder build.",
        " * PATCH_IMAGE_BASE and PATCH_IMAGE_CAPACITY are decoder-only device integration",
        " * configuration, not wire macros.",
        " * Do not edit this file by hand; regenerate with: make decoder-header",
        " */",
        "",
    ]
    public_names = {Path(rel).name for rel in headers}
    for rel in headers:
        chunks.append(f"/* ===== begin {rel} ===== */")
        chunks.append(filtered_text(rel, public_names).rstrip())
        chunks.append(f"/* ===== end {rel} ===== */")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", help="path to write, or - for stdout")
    parser.add_argument("headers", nargs="+", help="ordered public decoder headers to inline")
    args = parser.parse_args()

    text = generate(args.headers)
    if args.output == "-":
        print(text, end="")
    else:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        fd, temp_name = tempfile.mkstemp(
            dir=out.parent, prefix=f".{out.name}.", suffix=".tmp"
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as temp:
                temp.write(text)
                temp.flush()
                os.fsync(temp.fileno())
            os.replace(temp_name, out)
        finally:
            try:
                os.unlink(temp_name)
            except FileNotFoundError:
                pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
