#!/usr/bin/env python3
# Copyright (c) 2026 Mikhail Svarichevsky <mikhail@zeptobars.com>
# SPDX-License-Identifier: MIT
"""Generate the public single-file A1 decoder header."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import stat
import tempfile


ROOT = Path(__file__).resolve().parents[1]


def is_public_include(line: str, public_names: set[str]) -> bool:
    text = line.strip()
    if not text.startswith('#include "') or text.count('"') < 2:
        return False
    return text.split('"', 2)[1] in public_names


def filtered_text(rel: str, public_names: set[str]) -> str:
    path = ROOT / rel
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if is_public_include(line, public_names):
            out.append(f"/* {line.strip()} - inlined by gen_single_header.py */")
        else:
            out.append(line)
    return "\n".join(out).rstrip() + "\n"


def generate(headers: list[str]) -> str:
    chunks = [
        "/*",
        " * Generated public single-header A1 decoder.",
        " * Source headers, in order:",
        *(f" *   {rel}" for rel in headers),
        " * Include from one update translation unit to avoid duplicate decoder text.",
        " * Wire macro overrides MUST use the same names and values as the matching encoder build.",
        " * PATCH_IMAGE_BASE and PATCH_IMAGE_CAPACITY are decoder-only device integration",
        " * configuration, not wire macros.",
        " * Do not edit this file by hand; regenerate with: make decoder-header",
        " */",
        "",
    ]
    public_names = {Path(rel).name for rel in headers}
    for rel in headers:
        chunks.append(f"/* ===== begin {rel} ===== */")
        chunks.append(filtered_text(rel, public_names).rstrip())
        chunks.append(f"/* ===== end {rel} ===== */")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", help="path to write, or - for stdout")
    parser.add_argument("headers", nargs="+", help="ordered public decoder headers to inline")
    args = parser.parse_args()

    # Read and render every input before inspecting or creating the destination.  In
    # particular, a missing dependency must never disturb an already-published header.
    text = generate(args.headers)
    if args.output == "-":
        print(text, end="")
    else:
        out = Path(args.output)
        output_bytes = text.encode("utf-8")
        try:
            output_stat = out.lstat()
        except FileNotFoundError:
            output_mode = 0o644
        else:
            if not stat.S_ISREG(output_stat.st_mode):
                raise RuntimeError(f"refusing to replace non-regular output: {out}")
            output_mode = stat.S_IMODE(output_stat.st_mode)
            # A content-stable generation is a true no-op: preserve the inode,
            # timestamps, and exact existing permission mode.
            if out.read_bytes() == output_bytes:
                return 0

        out.parent.mkdir(parents=True, exist_ok=True)
        fd, temp_name = tempfile.mkstemp(
            dir=out.parent, prefix=f".{out.name}.", suffix=".tmp"
        )
        try:
            with os.fdopen(fd, "wb") as temp:
                temp.write(output_bytes)
                temp.flush()
                # mkstemp intentionally starts at 0600.  Publish new artifacts at
                # exactly 0644 regardless of umask, and preserve every permission
                # bit when atomically replacing an existing regular artifact.  Set
                # the mode after writing so a special bit cannot be cleared by a
                # later data write.
                os.fchmod(temp.fileno(), output_mode)
                os.fsync(temp.fileno())
            os.replace(temp_name, out)
        finally:
            try:
                os.unlink(temp_name)
            except FileNotFoundError:
                pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
